X: A
Square: B
O: NONE
Triangle: NONE
Start: Start
Select: NONE
R1: R
R2: NONE
R3: NONE
L1: Z
L2: L
L3: NONE
D-Up: NONE
D-Down: NONE
D-Left: NONE
D-Right: NONE
R-Up: C-Up
R-Down: C-Down
R-Left: C-Left
R-Right: C-Right